### ISSUE TITLE
Interactive markers glitch

### ISSUE THREAD

**Issue by tiagomfmadeira** [lardemua/AtlasCarCalibration#86] opened 2019-12-10 15:20 UTC
Interactive markers used while labelling the data suddenly disappear and then reappear with no obvious cause.

**Comment by miguelriemoliveira** [comment] 2019-12-10 22:42
@tiagomfmadeira , @afonsocastro and @eupedrosa , _deja vu_ ...

**Comment by miguelriemoliveira** [comment] 2019-12-10 22:51
I will take a look.

**Comment by miguelriemoliveira** [comment] 2019-12-10 23:09
I think this should be related to the detection of chessboards in the camera, or more specifically when this detection fails ... here's a printout of the time each interactive labeller takes to label the data

The screenshot was captured when the markers disappear from rviz. Notice how the chessboard latellers are taking 200 milisecs to "try to detect". 

I think this is what is delaying everything else ...

![image](https://user-images.githubusercontent.com/11350998/70576884-f0b06c80-1ba1-11ea-9a00-0b955a2cfa44.png)

**Comment by miguelriemoliveira** [comment] 2019-12-10 23:10
nots sure how to solve it though ... because this is inside the 

https://github.com/lardemua/AtlasCarCalibration/blob/954137668c1db7705eaa759b332b5fc093ee9b6b/interactive_calibration/src/interactive_calibration/interactive_data_labeler.py#L284-L285

**Comment by miguelriemoliveira** [comment] 2019-12-10 23:12
is it a problem really? What would be the expected behaviour @tiagomfmadeira and @eupedrosa ?

**Comment by eupedrosa** [comment] 2019-12-10 23:17
The interactive markers have a timeout? 

About detection times. Maybe it can be improved by #87. I will do some tests with the charuco board tomorrow and will report back.

**Comment by miguelriemoliveira** [comment] 2019-12-17 23:27
Yes, I am convinced that with the charuco  detection we should be fine. Lets close this one for now.

**Closed** 2019-12-17 23:27 UTC
Labels: bug
